create table if not exists public.areas (
  user_id text not null default 'clarice',
  id integer not null,
  name text not null,
  color text not null,
  primary key (user_id, id),
  unique (user_id, name)
);

create table if not exists public.commits (
  id bigint generated by default as identity primary key,
  user_id text not null default 'clarice',
  title text not null,
  description text not null default '',
  date date not null,
  area_id integer,
  type text not null default 'Reflection',
  tags text[] not null default '{}',
  seed text not null default '',
  created_at timestamptz not null default now(),
  foreign key (user_id, area_id) references public.areas(user_id, id)
);

alter table public.commits alter column area_id drop not null;

create table if not exists public.commit_impacts (
  id bigint generated by default as identity primary key,
  user_id text not null default 'clarice',
  commit_id bigint not null references public.commits(id) on delete cascade,
  area_id integer not null,
  impact_value numeric not null default 1,
  created_at timestamptz not null default now(),
  unique (user_id, commit_id, area_id),
  foreign key (user_id, area_id) references public.areas(user_id, id)
);

create table if not exists public.gratitudes (
  id bigint generated by default as identity primary key,
  user_id text not null default 'clarice',
  date date not null,
  text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.area_goals (
  user_id text not null default 'clarice',
  area_id integer not null,
  six_month_goal text not null default '',
  three_year_goal text not null default '',
  focus_points text not null default '',
  vision_text text not null default '',
  vision_images text[] not null default '{}',
  updated_at timestamptz not null default now(),
  primary key (user_id, area_id),
  foreign key (user_id, area_id) references public.areas(user_id, id)
);

create table if not exists public.tags (
  user_id text not null default 'clarice',
  name text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, name)
);

create table if not exists public.seeds (
  user_id text not null default 'clarice',
  name text not null,
  created_at timestamptz not null default now(),
  primary key (user_id, name)
);

create index if not exists commits_user_date_idx on public.commits(user_id, date desc);
create index if not exists commits_user_area_date_idx on public.commits(user_id, area_id, date desc);
create index if not exists commit_impacts_user_area_idx on public.commit_impacts(user_id, area_id);
create index if not exists commit_impacts_commit_idx on public.commit_impacts(commit_id);
create index if not exists gratitudes_user_date_idx on public.gratitudes(user_id, date desc);

insert into public.areas (user_id, id, name, color) values
  ('clarice', 1, 'Career', '#22c55e'),
  ('clarice', 2, 'English', '#3b82f6'),
  ('clarice', 3, 'Health', '#f59e0b'),
  ('clarice', 4, 'AI & Tech', '#a855f7'),
  ('clarice', 5, 'Thinking & Writing', '#ef4444'),
  ('clarice', 6, 'Money', '#ec4899'),
  ('clarice', 7, 'Relationships', '#14b8a6'),
  ('clarice', 8, 'Global', '#f97316'),
  ('clarice', 9, 'Assets', '#06b6d4')
on conflict (user_id, id) do update set
  name = excluded.name,
  color = excluded.color;

-- Backfill existing single-area commits. New analytics read from commit_impacts.
insert into public.commit_impacts (user_id, commit_id, area_id, impact_value)
select user_id, id, area_id, 1
from public.commits
where area_id is not null
on conflict (user_id, commit_id, area_id) do nothing;

-- Single-user MVP: allow the anon key to read and write Clarice's data.
-- Replace these permissive policies when authentication is added.
alter table public.areas enable row level security;
alter table public.commits enable row level security;
alter table public.commit_impacts enable row level security;
alter table public.gratitudes enable row level security;
alter table public.area_goals enable row level security;
alter table public.tags enable row level security;
alter table public.seeds enable row level security;

drop policy if exists "clarice areas access" on public.areas;
drop policy if exists "clarice commits access" on public.commits;
drop policy if exists "clarice commit impacts access" on public.commit_impacts;
drop policy if exists "clarice gratitudes access" on public.gratitudes;
drop policy if exists "clarice goals access" on public.area_goals;
drop policy if exists "clarice tags access" on public.tags;
drop policy if exists "clarice seeds access" on public.seeds;

create policy "clarice areas access" on public.areas for all using (user_id = 'clarice') with check (user_id = 'clarice');
create policy "clarice commits access" on public.commits for all using (user_id = 'clarice') with check (user_id = 'clarice');
create policy "clarice commit impacts access" on public.commit_impacts for all using (user_id = 'clarice') with check (user_id = 'clarice');
create policy "clarice gratitudes access" on public.gratitudes for all using (user_id = 'clarice') with check (user_id = 'clarice');
create policy "clarice goals access" on public.area_goals for all using (user_id = 'clarice') with check (user_id = 'clarice');
create policy "clarice tags access" on public.tags for all using (user_id = 'clarice') with check (user_id = 'clarice');
create policy "clarice seeds access" on public.seeds for all using (user_id = 'clarice') with check (user_id = 'clarice');

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.areas, public.commits, public.commit_impacts, public.gratitudes, public.area_goals, public.tags, public.seeds to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
